### ISSUE TITLE
Move groups of functions to dedicated files

### ISSUE THREAD

**Issue by sakkurax7** [ejnAjaK3VgnnHBLk/tedit#4]
Right now everything is in one file which has been fine but now the code is 800+ lines long.

**Comment by sakkurax7** [comment]
Remember that the functions need to have everything passed to them

**Comment by AkshantLanjewar** [comment]
no

**Comment by ejnAjaK3VgnnHBLk** [comment]
Dude why not

**Comment by sakkurax7** [comment]
#25 Resolves
